---
- name: Configure Raspberry Pi devices
  hosts: rpi_cluster
  become: yes
  tasks:
    - name: Set hostname
      ansible.builtin.hostname:
        name: "{{ inventory_hostname }}"

    - name: Configure mounts
      ansible.builtin.mount:
        path: "/path/to/mount"
        src: "/dev/device_name"
        fstype: "ext4"
        state: "mounted"

    - name: Install Docker
      ansible.builtin.package:
        name: "docker"
        state: "present"

    - name: Install Kubernetes packages
      ansible.builtin.package:
        name:
          - "kubelet"
          - "kubeadm"
          - "kubectl"
        state: "present"

# TODO user setup